In [ ]:
import numpy as np

# Create a 1xN dimensional array (feature vector)
feature_vector = np.array([1, 2, 3, 4, 5])

# Mean represents the average value of the  given vector space
mean = np.mean(feature_vector)

# varience represesnts the amount of difference between the mean to each element or number in the space.
variance = np.var(feature_vector)

print("Feature Vector:", feature_vector)
print("Mean:", mean)
print("Variance:", variance)

Feature Vector: [1 2 3 4 5]
Mean: 3.0
Variance: 2.0


In [ ]:
import numpy as np

#creating two vectors
vec1 = np.array([1,2,3,4,5])
vec2 = np.array([1,3,4,5,2])

mean1 = np.mean(vec1)
mean2 = np.mean(vec2)

if vec1.shape[0] != vec2.shape[0]:
    raise ValueError("Vectors must have the same dimension.")

#Covariance represents the relation between two variable and essentially a measure of variance.
covariance = np.mean((vec1-mean1) * (vec2-mean2))

print("Vector 1: ", vec1)
print("Vector 2: ", vec2)
print("Covariance: ", covariance)

Vector 1:  [1 2 3 4 5]
Vector 2:  [1 3 4 5 2]
Covariance:  0.8


In [ ]:
import numpy as np

#creating two vectors
vec1 = np.array([1,2,3,4,5])
vec2 = np.array([1,3,4,5,2])

mean1 = np.mean(vec1)
mean2 = np.mean(vec2)

if vec1.shape[0] != vec2.shape[0]:
    raise ValueError("Vectors must have the same dimension.")

#Covariance represents the relation between two variable and essentially a measure of variance.
covariance = np.mean((vec1-mean1) * (vec2-mean2))

std_vec1 = np.std(vec1)
std_vec2 = np.std(vec2)

#correlaiton quantifies the strength and direction of a linear relation between two variables
correlation = covariance / (std_vec1 * std_vec2)

print("Vector 1: ", vec1)
print("Vector 2: ", vec2)
print("Covariance: ", covariance)
print("Correlation: ", correlation)

Vector 1:  [1 2 3 4 5]
Vector 2:  [1 3 4 5 2]
Covariance:  0.8
Correlation:  0.3999999999999999


In [ ]:
import numpy as np

data_matrix = np.array([
    [2, 4, 6, 8],
    [1, 3, 5, 7],
    [5, 6, 2, 1]
])

covariance_matrix = np.cov(data_matrix, bias=False, rowvar=True)

correlation_matrix = np.corrcoef(data_matrix, rowvar=True)

print("Covariance Matrix:\n", covariance_matrix)
print("\nCorrelation Matrix:\n", correlation_matrix)

Covariance Matrix:
 [[ 6.66666667  6.66666667 -5.33333333]
 [ 6.66666667  6.66666667 -5.33333333]
 [-5.33333333 -5.33333333  5.66666667]]

Correlation Matrix:
 [[ 1.          1.         -0.86772183]
 [ 1.          1.         -0.86772183]
 [-0.86772183 -0.86772183  1.        ]]
